import Layout from "@/components/Layout";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import profilePic from "../../public/images/sementaraG.png";
import AnimatedText from "@/components/AnimatedText";
import LinkArrow from "@/icons/LinkArrow";
import HireMe from "@/components/HireMe";
import ParticlesContainer from "@/components/ParticlesContainer";
import AmogusParticles from "@/components/AmogusParticles";

export default function Home() {
  return (
    <>
      <Head>
        <title>| WiNF =&gt; Solver | </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0 z-2">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/3 z-10">
              <Image src={profilePic} alt="WiNF" className="w-full h-auto " />
            </div>

            <ParticlesContainer className="z-1" />

            <div className="w-1/2  flex flex-col items-center self-center z-7 ">
              <AnimatedText
                text="World is Wonderfull with Design. "
                className="!text-6xl"
              />
              <p className="my-4 text-base font-medium ">
                Hello, my name is Wildan Nur Fauzan. I&apos;m a student based in
                Yogyakarta with a passion for creating innovative solutions to
                real-world problems. I have been studying in UPNVY 2023 until
                now, I choose major bachelor&apos;s degree of Accounting.
                Outside of lecture, I enjoy programming, editing, and online or
                offline volunteering . I am excited to connect with like-minded
                professionals and continue to learn and grow in my field.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/CV ATS.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                   hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:vellvester@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe></HireMe>
      </main>
    </>
  );
}
